# Generated by Django 5.2.15 on 2026-07-02 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(help_text='The outlaw / debtor / cargo description', max_length=255)),
                ('reward', models.DecimalField(decimal_places=2, help_text='The bounty / tab amount / declared value', max_digits=10)),
                ('status', models.CharField(choices=[('wanted', 'Wanted'), ('captured', 'Captured')], default='wanted', max_length=10)),
                ('danger_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('extreme', 'Extreme')], default='medium', max_length=10)),
                ('last_seen_at', models.CharField(blank=True, help_text='Last known location', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bounties',
                'ordering': ['-created_at'],
            },
        ),
    ]
